//! `TypeScriptGenerator` — generates a typed ESM module (`.ts` + `.d.ts`).
//!
//! The generated module:
//!
//! - Is named `<cli_name>.ts` (source) and `<cli_name>.d.ts` (declarations).
//! - Contains `BRIDGE` and `TOKEN` constants.
//! - Exports one `async function <camelCaseName>(...)` per upstream tool with:
//!   - Required params positional; optional params with `?` suffix and `undefined` default.
//!   - Return type `Promise<string>`.
//! - Uses the Fetch API (`fetch`) for HTTP calls — no additional dependencies.
//! - Contains a `// generated by mcp-compressor — do not edit manually` header.
//!
//! Tool name convention: `snake_case → camelCase`
//! e.g. `get_confluence_page → getConfluencePage`.

use std::path::PathBuf;

use crate::client_gen::generator::{ClientGenerator, GeneratorConfig};
use crate::Error;

pub struct TypeScriptGenerator;

impl ClientGenerator for TypeScriptGenerator {
    fn generate(&self, config: &GeneratorConfig) -> Result<Vec<PathBuf>, Error> {
        todo!()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::client_gen::generator::test_helpers::{make_config, make_config_multiword_tool};
    use crate::client_gen::ClientGenerator;
    use std::ffi::OsStr;
    use std::fs;

    // Helper: find the `.ts` (non-declaration) path in a list of paths.
    fn find_ts(paths: &[PathBuf]) -> &PathBuf {
        paths
            .iter()
            .find(|p| {
                p.extension() == Some(OsStr::new("ts"))
                    && !p.to_str().unwrap_or("").ends_with(".d.ts")
            })
            .expect("no .ts file found")
    }

    // Helper: find the `.d.ts` declaration path.
    fn find_dts(paths: &[PathBuf]) -> &PathBuf {
        paths
            .iter()
            .find(|p| p.to_str().unwrap_or("").ends_with(".d.ts"))
            .expect("no .d.ts file found")
    }

    // ------------------------------------------------------------------
    // File creation
    // ------------------------------------------------------------------

    /// generate() returns exactly two paths: `.ts` and `.d.ts`.
    #[test]
    fn generate_returns_two_files() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = TypeScriptGenerator.generate(&config).unwrap();
        assert_eq!(paths.len(), 2, "expected exactly two generated files (.ts and .d.ts)");
    }

    /// A `.ts` source file is produced.
    #[test]
    fn generates_ts_source_file() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = TypeScriptGenerator.generate(&config).unwrap();
        let _ = find_ts(&paths); // panics if not found
    }

    /// A `.d.ts` declaration file is produced.
    #[test]
    fn generates_dts_declaration_file() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = TypeScriptGenerator.generate(&config).unwrap();
        let _ = find_dts(&paths); // panics if not found
    }

    /// The `.ts` file is named `<cli_name>.ts`.
    #[test]
    fn ts_file_named_after_cli_name() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = TypeScriptGenerator.generate(&config).unwrap();
        let ts = find_ts(&paths);
        assert_eq!(ts.file_name(), Some(OsStr::new("my-server.ts")));
    }

    /// The `.d.ts` file is named `<cli_name>.d.ts`.
    #[test]
    fn dts_file_named_after_cli_name() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = TypeScriptGenerator.generate(&config).unwrap();
        let dts = find_dts(&paths);
        assert_eq!(dts.file_name(), Some(OsStr::new("my-server.d.ts")));
    }

    /// Both generated files actually exist on disk.
    #[test]
    fn all_files_exist() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = TypeScriptGenerator.generate(&config).unwrap();
        for p in &paths {
            assert!(p.exists(), "expected file to exist: {p:?}");
        }
    }

    // ------------------------------------------------------------------
    // .ts content — header
    // ------------------------------------------------------------------

    /// The `.ts` file starts with the "do not edit manually" comment.
    #[test]
    fn ts_has_do_not_edit_header() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = TypeScriptGenerator.generate(&config).unwrap();
        let ts = find_ts(&paths);
        let content = fs::read_to_string(ts).unwrap();
        assert!(content.contains("do not edit"), "expected 'do not edit' header");
    }

    // ------------------------------------------------------------------
    // .ts content — constants
    // ------------------------------------------------------------------

    /// The `.ts` file contains the session `TOKEN` constant.
    #[test]
    fn ts_contains_token_constant() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = TypeScriptGenerator.generate(&config).unwrap();
        let ts = find_ts(&paths);
        let content = fs::read_to_string(ts).unwrap();
        assert!(content.contains(&config.token), "token not found");
        assert!(content.contains("TOKEN"), "TOKEN constant not found");
    }

    /// The `.ts` file contains the `BRIDGE` URL constant.
    #[test]
    fn ts_contains_bridge_constant() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = TypeScriptGenerator.generate(&config).unwrap();
        let ts = find_ts(&paths);
        let content = fs::read_to_string(ts).unwrap();
        assert!(content.contains(&config.bridge_url), "bridge URL not found");
        assert!(content.contains("BRIDGE"), "BRIDGE constant not found");
    }

    // ------------------------------------------------------------------
    // .ts content — function exports
    // ------------------------------------------------------------------

    /// Each upstream tool produces an `export async function <name>` entry.
    #[test]
    fn ts_exports_async_function_per_tool() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = TypeScriptGenerator.generate(&config).unwrap();
        let ts = find_ts(&paths);
        let content = fs::read_to_string(ts).unwrap();
        assert!(content.contains("export async function fetch("), "'fetch' function not found");
        assert!(content.contains("export async function search("), "'search' function not found");
    }

    /// Functions return `Promise<string>`.
    #[test]
    fn ts_functions_return_promise_string() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = TypeScriptGenerator.generate(&config).unwrap();
        let ts = find_ts(&paths);
        let content = fs::read_to_string(ts).unwrap();
        assert!(content.contains("Promise<string>"), "Promise<string> return type not found");
    }

    /// A multi-word snake_case tool name is exported as camelCase.
    #[test]
    fn ts_multiword_tool_name_is_camel_case() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config_multiword_tool(dir.path());
        let paths = TypeScriptGenerator.generate(&config).unwrap();
        let ts = find_ts(&paths);
        let content = fs::read_to_string(ts).unwrap();
        // "get_confluence_page" → "getConfluencePage"
        assert!(
            content.contains("getConfluencePage"),
            "expected camelCase function name 'getConfluencePage', got: {content:?}",
        );
    }

    // ------------------------------------------------------------------
    // .d.ts content
    // ------------------------------------------------------------------

    /// The `.d.ts` file contains `export` declarations.
    #[test]
    fn dts_contains_exports() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = TypeScriptGenerator.generate(&config).unwrap();
        let dts = find_dts(&paths);
        let content = fs::read_to_string(dts).unwrap();
        assert!(content.contains("export"), "no exports found in .d.ts");
    }

    /// The `.d.ts` file declares the same function names as the `.ts` source.
    #[test]
    fn dts_declares_same_functions_as_ts() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = TypeScriptGenerator.generate(&config).unwrap();
        let dts = find_dts(&paths);
        let content = fs::read_to_string(dts).unwrap();
        assert!(content.contains("fetch"), "'fetch' not declared in .d.ts");
        assert!(content.contains("search"), "'search' not declared in .d.ts");
    }
}
