site_name: mcp-compressor
repo_url: https://github.com/atlassian-labs/mcp-compressor
site_url: https://atlassian-labs.github.io/mcp-compressor
site_description: An MCP server wrapper for reducing tokens consumed by MCP tools.
site_author: Tim Esler
edit_uri: edit/main/docs/
repo_name: atlassian-labs/mcp-compressor
copyright: Maintained by <a href="https://atlassian.com">atlassian</a>.

nav:
  - Home: index.md
  - TypeScript: typescript.md
  - Rust Core Design: rust-core-design.md
  - Modules: modules.md
plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          paths: ["mcp_compressor"]
theme:
  name: material
  logo: https://raw.githubusercontent.com/atlassian-forks/SWE-PolyBench/refs/heads/main/rovo-dev-logo.svg
  favicon: https://raw.githubusercontent.com/atlassian-forks/SWE-PolyBench/refs/heads/main/rovo-dev-logo.svg
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/atlassian-labs/mcp-compressor
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mcp-compressor

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
