"""CLI script generator for CLI mode.

Generates an executable script (Python on Unix, .cmd batch on Windows)
that forwards arguments to the local mcp-compressor bridge HTTP server.
"""

from __future__ import annotations

import os
import platform
import stat
from pathlib import Path

_IS_WINDOWS = platform.system() == "Windows"

# Ordered list of candidate directories for the generated CLI script.
# The first one that exists AND is on the user's PATH is used.
# If none match, the current working directory is used instead.
_UNIX_CANDIDATE_SCRIPT_DIRS: list[str] = [
    "~/.local/bin",
    "~/bin",
    "/usr/local/bin",
    "/opt/homebrew/bin",
]

_WINDOWS_CANDIDATE_SCRIPT_DIRS: list[str] = [
    "~/AppData/Local/Microsoft/WindowsApps",
    "~/.local/bin",
]


def find_script_dir() -> tuple[Path, bool]:
    """Find the best directory for writing the generated CLI script.

    Tries each candidate in the platform-appropriate list in order, choosing the
    first that both exists and is present on the user's ``PATH``.  Falls back
    to the current working directory when none qualify.

    Returns:
        A 2-tuple of:
          - the chosen directory as a ``Path``
          - ``True`` if the directory is on PATH (script can be run without ``./``),
            ``False`` if the CWD fallback was used.
    """
    candidates = _WINDOWS_CANDIDATE_SCRIPT_DIRS if _IS_WINDOWS else _UNIX_CANDIDATE_SCRIPT_DIRS
    path_dirs = {Path(p).expanduser().resolve() for p in os.environ.get("PATH", "").split(os.pathsep) if p}

    for candidate in candidates:
        expanded = Path(candidate).expanduser().resolve()
        if expanded in path_dirs and expanded.exists():
            return expanded, True

    return Path.cwd(), False


def generate_cli_script(cli_name: str, bridge_port: int, script_dir: Path | None = None) -> tuple[Path, bool]:
    """Generate an executable script that acts as a CLI for the local bridge.

    On Unix, generates a Python3 script with a shebang. On Windows, generates a
    ``.cmd`` batch script that internally calls PowerShell for the HTTP request.

    Args:
        cli_name: The CLI command name (e.g. "atlassian").
        bridge_port: The local port the bridge HTTP server is listening on.
        script_dir: Directory in which to write the script. If None, ``find_script_dir``
            is used to pick the best available location.

    Returns:
        A 2-tuple of:
          - the ``Path`` to the generated script
          - ``True`` if the script dir is on PATH (no ``./`` needed)
    """
    if script_dir is not None:
        script_dir_path = script_dir
        on_path = True  # caller supplied explicit dir; trust them
    else:
        script_dir_path, on_path = find_script_dir()

    script_dir_path.mkdir(parents=True, exist_ok=True)

    if _IS_WINDOWS:
        return _generate_windows_script(cli_name, bridge_port, script_dir_path, on_path)
    return _generate_unix_script(cli_name, bridge_port, script_dir_path, on_path)


def _generate_unix_script(cli_name: str, bridge_port: int, script_dir: Path, on_path: bool) -> tuple[Path, bool]:
    """Generate a Unix-compatible Python3 CLI script."""
    script_path = script_dir / cli_name
    bridge_url = f"http://127.0.0.1:{bridge_port}"

    script_content = f"""\
#!/usr/bin/env python3
# Auto-generated by mcp-compressor. Do not edit manually.
# CLI name: {cli_name}
# Bridge:   {bridge_url}

import json
import sys
import urllib.error
import urllib.request

BRIDGE = "{bridge_url}"

def main():
    argv = sys.argv[1:]
    payload = json.dumps({{"argv": argv}}).encode()
    req = urllib.request.Request(
        BRIDGE + "/exec",
        data=payload,
        headers={{"Content-Type": "application/json"}},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req) as resp:
            sys.stdout.write(resp.read().decode())
            sys.exit(0)
    except urllib.error.HTTPError as exc:
        sys.stderr.write(exc.read().decode())
        sys.exit(1)
    except urllib.error.URLError:
        sys.stderr.write(
            f"error: could not connect to mcp-compressor bridge at {{BRIDGE}}\\n"
            "Is mcp-compressor running in --cli-mode?\\n"
        )
        sys.exit(1)

if __name__ == "__main__":
    main()
"""

    script_path.write_text(script_content)
    current_mode = script_path.stat().st_mode
    script_path.chmod(current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return script_path, on_path


def _generate_windows_script(cli_name: str, bridge_port: int, script_dir: Path, on_path: bool) -> tuple[Path, bool]:
    """Generate a Windows-compatible .cmd CLI script.

    Uses a thin batch wrapper that internally calls PowerShell for the HTTP
    request.  This avoids execution-policy issues that ``.ps1`` scripts face
    and allows the script to be run directly from PATH without an extension.
    """
    script_path = script_dir / f"{cli_name}.cmd"
    bridge_url = f"http://127.0.0.1:{bridge_port}"

    # The batch portion collects all arguments into a variable, then hands off
    # to an inline PowerShell command that JSON-encodes argv and POSTs to the
    # bridge.
    script_content = f"""\
@echo off
REM Auto-generated by mcp-compressor. Do not edit manually.
REM CLI name: {cli_name}
REM Bridge:   {bridge_url}

set "BRIDGE={bridge_url}"

powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$argv = @(%*); " ^
  "$payload = @{{ argv = $argv }} | ConvertTo-Json -Compress; " ^
  "try {{ " ^
  "  $r = Invoke-WebRequest -Uri '%BRIDGE%/exec' -Method POST " ^
  "    -ContentType 'application/json' -Body $payload -UseBasicParsing -ErrorAction Stop; " ^
  "  Write-Host $r.Content; " ^
  "  exit 0 " ^
  "}} catch {{ " ^
  "  $e = $_.Exception; " ^
  "  if ($e -is [System.Net.WebException] -and $e.Response) {{ " ^
  "    $sr = New-Object System.IO.StreamReader($e.Response.GetResponseStream()); " ^
  "    Write-Error $sr.ReadToEnd(); exit 1 " ^
  "  }}; " ^
  "  Write-Error 'error: could not connect to mcp-compressor bridge at %BRIDGE%'; " ^
  "  Write-Error 'Is mcp-compressor running in --cli-mode?'; exit 1 " ^
  "}}"
"""

    script_path.write_text(script_content)
    return script_path, on_path
